"""
supabase_schema_init.py — Автоматическое создание схемы Supabase для нового проекта.

Вызывается из workflow /create при создании нового проекта.
Создаёт изолированную PostgreSQL-схему в Supabase.

Использование:
  python .agent/scripts/supabase_schema_init.py --project-name "my_project"
  python .agent/scripts/supabase_schema_init.py --project-name "my_project" --dry-run

Что делает:
  1. Нормализует имя проекта → schema name (snake_case, только [a-z0-9_])
  2. Генерирует SQL для создания схемы
  3. Выполняет SQL через Supabase REST API (service_role)
  4. Создаёт search_path для удобства
  5. Логирует результат

Требования:
  - SUPABASE_URL в окружении
  - SUPABASE_SERVICE_ROLE_KEY в окружении
  - requests library
"""

import argparse
import logging
import os
import re
import sys
import json
from datetime import datetime, timezone

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)


def normalize_schema_name(project_name: str) -> str:
    """
    Нормализует имя проекта в валидное имя PostgreSQL-схемы.
    
    - Транслитерация кириллицы (базовая)
    - Замена пробелов и спецсимволов на _
    - Lowercase
    - Префикс prj_ для изоляции
    - Максимум 63 символа (лимит PostgreSQL)
    """
    # Simple transliteration map for common Cyrillic characters
    translit_map = {
        'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e',
        'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'y', 'к': 'k',
        'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r',
        'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'kh', 'ц': 'ts',
        'ч': 'ch', 'ш': 'sh', 'щ': 'shch', 'ъ': '', 'ы': 'y', 'ь': '',
        'э': 'e', 'ю': 'yu', 'я': 'ya',
    }

    name = project_name.lower().strip()

    # Transliterate Cyrillic
    result = []
    for char in name:
        if char in translit_map:
            result.append(translit_map[char])
        else:
            result.append(char)
    name = "".join(result)

    # Replace non-alphanumeric with underscore
    name = re.sub(r"[^a-z0-9]", "_", name)

    # Collapse multiple underscores
    name = re.sub(r"_+", "_", name)

    # Strip leading/trailing underscores
    name = name.strip("_")

    # Add project prefix for namespace isolation
    schema_name = f"prj_{name}"

    # PostgreSQL identifier limit
    if len(schema_name) > 63:
        schema_name = schema_name[:63]

    return schema_name


def generate_schema_sql(schema_name: str) -> str:
    """
    Генерирует SQL для создания схемы с базовой структурой.
    """
    return f"""
-- ============================================================
-- Schema: {schema_name}
-- Created: {datetime.now(timezone.utc).isoformat()}
-- Generated by: OSUI V7.5 /create workflow
-- ============================================================

-- 1. Create schema (idempotent)
CREATE SCHEMA IF NOT EXISTS {schema_name};

-- 2. Grant access to key roles
GRANT USAGE ON SCHEMA {schema_name} TO postgres, anon, authenticated, service_role;

-- 3. Default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA {schema_name}
  GRANT ALL ON TABLES TO postgres, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA {schema_name}
  GRANT SELECT ON TABLES TO anon;

ALTER DEFAULT PRIVILEGES IN SCHEMA {schema_name}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated;

-- 4. Default privileges for future sequences
ALTER DEFAULT PRIVILEGES IN SCHEMA {schema_name}
  GRANT USAGE, SELECT ON SEQUENCES TO postgres, anon, authenticated, service_role;

-- 5. Default privileges for future functions
ALTER DEFAULT PRIVILEGES IN SCHEMA {schema_name}
  GRANT EXECUTE ON FUNCTIONS TO postgres, anon, authenticated, service_role;

-- 6. Project metadata table (for tracking)
CREATE TABLE IF NOT EXISTS {schema_name}._project_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO {schema_name}._project_meta (key, value)
VALUES 
  ('schema_name', '{schema_name}'),
  ('created_at', '{datetime.now(timezone.utc).isoformat()}'),
  ('created_by', 'osui_v75_create_workflow')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();

-- 7. Enable RLS on metadata table
ALTER TABLE {schema_name}._project_meta ENABLE ROW LEVEL SECURITY;

-- 8. Policy: only service_role can read metadata
CREATE POLICY IF NOT EXISTS "service_role_read_meta"
  ON {schema_name}._project_meta
  FOR SELECT
  TO service_role
  USING (true);
""".strip()


def execute_sql_via_rpc(sql: str, supabase_url: str, service_key: str) -> dict:
    """
    Выполняет SQL через Supabase RPC (pg_query или прямой REST endpoint).
    Используем supabase-selfhosted MCP как основной путь,
    fallback — прямой HTTP вызов.
    """
    try:
        import requests
    except ImportError:
        logger.error("Библиотека 'requests' не установлена. pip install requests")
        return {"success": False, "error": "requests not installed"}

    # Use the SQL endpoint directly
    url = f"{supabase_url}/rest/v1/rpc/exec_sql"
    headers = {
        "apikey": service_key,
        "Authorization": f"Bearer {service_key}",
        "Content-Type": "application/json",
        "Prefer": "return=representation",
    }

    resp = requests.post(
        url,
        headers=headers,
        json={"query": sql},
        timeout=30,
    )

    if resp.status_code in (200, 201, 204):
        return {"success": True, "status_code": resp.status_code}

    # Fallback: try direct pgMeta API
    logger.warning(
        f"RPC exec_sql returned {resp.status_code}. "
        "Trying alternative approach..."
    )

    # Alternative: use pg-meta query endpoint
    meta_url = f"{supabase_url}/pg/query"
    resp2 = requests.post(
        meta_url,
        headers={
            "apikey": service_key,
            "Authorization": f"Bearer {service_key}",
            "Content-Type": "application/json",
        },
        json={"query": sql},
        timeout=30,
    )

    if resp2.status_code in (200, 201, 204):
        return {"success": True, "status_code": resp2.status_code}

    return {
        "success": False,
        "status_code": resp2.status_code,
        "error": resp2.text[:500],
    }


def save_migration_file(schema_name: str, sql: str, project_dir: str) -> str:
    """
    Сохраняет SQL как файл миграции в supabase/migrations/.
    """
    migrations_dir = os.path.join(project_dir, "supabase", "migrations")
    os.makedirs(migrations_dir, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    filename = f"{timestamp}_create_schema_{schema_name}.sql"
    filepath = os.path.join(migrations_dir, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(sql)

    logger.info(f"Миграция сохранена: {filepath}")
    return filepath


def main():
    parser = argparse.ArgumentParser(
        description="Создание схемы Supabase для нового проекта OSUI"
    )
    parser.add_argument(
        "--project-name",
        required=True,
        help="Имя проекта (будет нормализовано в snake_case)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Только показать SQL, не выполнять"
    )
    parser.add_argument(
        "--project-dir",
        default=".",
        help="Корневая директория проекта (для сохранения миграции)"
    )
    parser.add_argument(
        "--output-json",
        action="store_true",
        help="Вывести результат в JSON (для автоматизации)"
    )

    args = parser.parse_args()

    # Normalize project name to schema name
    schema_name = normalize_schema_name(args.project_name)
    logger.info(f"Проект: '{args.project_name}' → Схема: '{schema_name}'")

    # Generate SQL
    sql = generate_schema_sql(schema_name)

    if args.dry_run:
        print("\n--- DRY RUN: SQL для создания схемы ---\n")
        print(sql)
        print(f"\n--- Схема: {schema_name} ---")

        result = {
            "schema_name": schema_name,
            "project_name": args.project_name,
            "dry_run": True,
            "sql": sql,
        }

        if args.output_json:
            print(json.dumps(result, ensure_ascii=False, indent=2))
        return

    # Load credentials
    supabase_url = os.getenv("SUPABASE_URL")
    service_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

    if not supabase_url or not service_key:
        logger.error(
            "Не заданы SUPABASE_URL и/или SUPABASE_SERVICE_ROLE_KEY. "
            "Добавьте их в .env или окружение."
        )
        # Still save migration file locally
        migration_path = save_migration_file(
            schema_name, sql, args.project_dir
        )
        logger.info(
            "SQL сохранён как миграция. Выполните вручную или "
            "через MCP supabase-selfhosted."
        )

        result = {
            "schema_name": schema_name,
            "project_name": args.project_name,
            "executed": False,
            "migration_file": migration_path,
            "reason": "missing_credentials",
        }

        if args.output_json:
            print(json.dumps(result, ensure_ascii=False, indent=2))
        sys.exit(1)

    # Save migration file
    migration_path = save_migration_file(schema_name, sql, args.project_dir)

    # Execute SQL
    logger.info("Выполняю SQL на Supabase...")
    exec_result = execute_sql_via_rpc(sql, supabase_url, service_key)

    if exec_result["success"]:
        logger.info(f"✅ Схема '{schema_name}' успешно создана!")
    else:
        logger.warning(
            f"⚠️ Автоматическое выполнение не удалось: "
            f"{exec_result.get('error', 'unknown')}. "
            f"SQL сохранён в {migration_path}. "
            f"Выполните вручную через MCP supabase-selfhosted."
        )

    result = {
        "schema_name": schema_name,
        "project_name": args.project_name,
        "executed": exec_result["success"],
        "migration_file": migration_path,
    }

    if args.output_json:
        print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
